=== AjayBhatta16/portfolio/_schemas/contact.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "description": "The name of the contact method"
        },
        "iconClassList": {
            "type": "string",
            "description": "The FontAwesome class list for the contact method's icon"
        },
        "linkDisplayText": {
            "type": "string",
            "description": "The text to display for the contact method"
        },
        "linkUrl": {
            "type": "string",
            "description": "The URL for the contact method"
        },
        "copyText": {
            "type": "string",
            "description": "The text to copy to the clipboard for the contact method"
        }
    }
}

=== AjayBhatta16/portfolio/public/contact-list.json
[
    {
        "name": "Buy Me A Coffee",
        "iconClassList": "fas fa-coffee",
        "linkDisplayText": "ajaybhatta49",
        "linkUrl": "https://buymeacoffee.com/ajaybhatta49?new=1"
    },
    {
        "name": "Email",
        "iconClassList": "fas fa-envelope",
        "linkDisplayText": "ajay.bhattacharyya.16@gmail.com",
        "linkUrl": "mailto:ajay.bhattacharyya.16@gmail.com"
    },
    {
        "name": "Phone",
        "iconClassList": "fas fa-phone",
        "linkDisplayText": "(585) 851-4522",
        "linkUrl": "tel:+15858514522"
    },
    {
        "name": "GitHub",
        "iconClassList": "fab fa-github",
        "linkDisplayText": "AjayBhatta16",
        "linkUrl": "https://github.com/AjayBhatta16"
    },
    {
        "name": "LinkedIn",
        "iconClassList": "fab fa-linkedin-in",
        "linkDisplayText": "Ajay Bhattacharyya",
        "linkUrl": "https://www.linkedin.com/in/ajaybhatta49/"
    }
]
